### ISSUE TITLE
ipのリストを扱えるようにする

### ISSUE THREAD

**Issue by nexryai** [nexryai/lance-light#10]
```
ipset:
   hoge:
        - 0.0.0.0
        - 1.1.1.1
   fuge:
        - 2.2.2.2
        - 3.3.3.3
```
みたいに設定してルールを簡素化できるようにする
